### ISSUE TITLE
Not clicking "select club" button

### ISSUE THREAD

**Issue by ammrlc** [chakrakan/fit4less-autobooker#13]
Hi chakrakan,

I love this autobooker!! One little problem I encountered was when having one booked session the "select club" button was off the screen and the booker was not able to click the button. I added a scrolling script to scroll down the page, which fixed the issue on my end.

**Comment by chakrakan** [comment]
Hey @ammrlc!

I'm glad you find this useful! I have a general scroll to bottom in the script as seen on this [line](https://github.com/chakrakan/fit4less-autobooker/blob/4290cc1d8a9f0f7ed1336a845b860850aed9d910/autobooker.py#L56), but could you share a screen-shot/gif of your situation, and the fix you employed? You can create a PR if you want :)
