### ISSUE TITLE
Booking for 2:30 PM books for 12:30Pm

### ISSUE THREAD

**Issue by NajibNour** [chakrakan/fit4less-autobooker#4]

**Comment by NajibNour** [comment]
A little issue when booking for 2:30pm ad env var as 2:30 PM. When it finds 12:30 PM it considers it a match and books at that time.

**Comment by chakrakan** [comment]
Thanks for pointing it out, I missed this edge-case!

The current implementation does a lazy evaluation for the text-field using pythonic `in` instead of an exact truthy match for the timeslot.

I'll push a fix by tonight!

**Comment by NajibNour** [comment]
Thank you very much for creating this BTW! This is amazing and makes my life so much easier!

**Comment by chakrakan** [comment]
@NajibNour so upon investigating further, it seems that Fit4Less has reduced their booking-hours for gyms.

I checked with random gyms for 11th Oct, and it seems only the following time-slots are available:

<img width="741" alt="Screen Shot 2020-10-09 at 6 34 54 PM" src="https://user-images.githubusercontent.com/57884127/95636822-217d5e80-0a5e-11eb-9a0b-e9a3aafe1cd2.png">

I'm gonna put in a fix for future, but for now, I think you're limited to using these time slots.
